login/urls.py
from django.conf.urls import url
from .views import *

# /sol
from .custom_auth import auth_login, auth_logout

urlpatterns = [
	url(r'^$', index, name='index'),

    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout')
    ]

mblepp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import profile_app.urls as profile
import riwayat.urls as riwayat
import login.urls as login
import status.urls as status

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(profile, namespace='profile')),
    url(r'^riwayat/', include(riwayat, namespace='riwayat')),
    url(r'^login/', include(login, namespace='login')),
    url(r'^status/', include(status, namespace='status')),
    url(r'^$', RedirectView.as_view(url="/login/", permanent="true"), name='index'),
]

status/urls.py
from django.conf.urls import url
from .views import index, add_status, delete_status

urlpatterns = [
	url(r'^(?P<username>.*)/$', index, name='index'),
	url(r'^add_status', add_status, name='add_status'),
]

status/models.py
from django.db import models
from login.models import User

class StatusKu(models.Model):
	pengguna = models.ForeignKey(User, on_delete=models.CASCADE)
	description = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)

status/forms.py
from django import forms

class Form_status(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    description_attrs = {
        'type': 'text',
        'cols': 100,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Apa yang anda pikirkan?'
    }

    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

status/views.py
from django.shortcuts import render
from .models import StatusKu
from .forms import Form_status
from login.models import User
from django.http import HttpResponseRedirect
# Create your views here.
response = {}
def index(request, username):
	if get_data_user(request, 'user_login'):
		name = request.session.get('user_login', None)
		set_data_for_session(request)
		kode_identitas = get_data_user(request, 'kode_identitas')
		pengguna = User.objects.get(kode_identitas = kode_identitas)


		if (name == username):
			response['show_form'] = True
		else:
			response['show_form'] = False
		print('pengguna')
		response['test'] = 'hai halo'
		response['login'] = True
		statusnya = StatusKu.objects.filter(pengguna = pengguna).order_by('-id')
		response['status_form'] = Form_status
		response['status'] = statusnya
		html = 'status/status.html'
		return render(request, html, response)
	else:
		response['login'] = False
		html = 'login/login.html'
		return render(request, html, response)


def add_status(request):
	form = Form_status(request.POST or None)
	#set_data_for_session(request)
	

	#kode_identitas = get_data_user(request, 'kode_identitas')
	#pengguna = User.objects.get(kode_identitas = kode_identitas)
	if(request.method == 'POST' and form.is_valid()):
		username = request.session['user_login']
		pengguna = User.objects.get(nama = username)
		print('dia adalah=>',pengguna)
		response['description'] = request.POST['description']
		status = StatusKu(pengguna = pengguna, description=response['description'])
		#status.pengguna = pengguna
		status.save()
		return HttpResponseRedirect('/status/'+username)
	else:
		return HttpResponseRedirect('/status/'+username)

def delete_status(request, id_status):
	print('delete something')
	status = StatusKu.objects.get(pk = id_status)
	status.delete()
	return HttpResponseRedirect('/status/'+username)

def get_data_user(request, tipe):
	data = None
	if tipe == "user_login" and 'user_login' in request.session:
		data = request.session['user_login']
	elif tipe == "kode_identitas" and 'kode_identitas' in request.session:
		data = request.session['kode_identitas']
	elif tipe == "role" and 'role' in request.session:
		data = request.session['role']


	return data

def set_data_for_session(request):
	response['author'] = get_data_user(request, 'user_login')
	response['kode_identitas'] = request.session['kode_identitas']
	response['role'] = request.session['role']

status/templates/status/status.html
{% extends "login/layout/base.html" %}

{% block content %}
{% if show_form %}
<section name="input-list" id="update-status-box">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-sm-offset-2">

                <form id="form" method="POST" action="{% url 'status:add_status' %}">
                    <h2><strong>Update status...</strong></h2>
                    {% csrf_token %}
                    {{ status_form }}
                    <input id="submit" type="submit" class="btn btn-md btn-info" value="Submit">
                    <br>
                </form>
            </div>
        </div>
        
    </div>
</section>
{% endif %}

<section name="my-list" id="show-status" style="padding-bottom: 20px; padding-top: 0px">
    {% if status %}
        {% for data in status %}
            <div class="container" style="padding-top: 0px">
                <div class="row">
                    <div class="col-sm-8 col-sm-offset-2">
                        <div class="media" style="padding: 40px">
                            <div class="media-left">
                                <img src="https://assets.teenvogue.com/photos/59922529fc885e5cc9aba96e/master/pass/GettyImages-546939180.jpg" class="media-object img-circle" style="width:75px"><!--foto nanti diganti dgn foto di hal profile-->
                            </div>
                            <div class="media-body">
                                
                                <h4 class="media-heading"><strong>{{author}}</strong> <small><i>Posted on {{data.created_date}}</i></small></h4><!--nama nanti diganti dgn nama di hal profile-->
                                <p>{{data.description}}</p>
                                

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
         <div class="container text-center"  style="padding-top: 15px;">
            <div class="row">
                <div class="col-sm-8 col-sm-offset-2">
                    <div id="empty" class="alert alert-danger">
                        <strong>Oops!</strong> Anda belum membuat status apapun.
                    </div>
                    
                </div>
            </div>
            
        </div>
    {% endif %}
    
</section>

{% endblock %}