login/urls.py
from django.conf.urls import url
from .views import *

# /sol
from .custom_auth import auth_login, auth_logout

urlpatterns = [
	url(r'^$', index, name='index'),

    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout')
    ]

mblepp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import profile_app.urls as profile
import riwayat.urls as riwayat
import login.urls as login
import status.urls as status

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(profile, namespace='profile')),
    url(r'^riwayat/', include(riwayat, namespace='riwayat')),
    url(r'^login/', include(login, namespace='login')),
    url(r'^status/', include(status, namespace='status')),
    url(r'^$', RedirectView.as_view(url="/login/", permanent="true"), name='index'),
]

login/models.py
from django.db import models

# Create your models here.
class User (models.Model):
	nama = models.CharField('Nama', max_length=200)
	kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True)
	role = models.CharField('Role', max_length=100)

login/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import json
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from .models import User


# Create your views here.
response = {'logged_in' : False}
def index(request):
	print ("#==> masuk index")
	if 'user_login' in request.session:
		response['logged_in'] = True
		return HttpResponseRedirect(reverse('profile:index'))
	else:
		response['login'] = False;
		html = 'login/login.html'
		return render(request, html, response)

login/templates/login/partials/header.html
 
{% if login %}
 <div class="navbar navbar-inverse navbar-fixed-top" role="navigation" >
    <div class="container"> 
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span> 
            </button>
            <a href="/login/" class="navbar-brand">JobSeeker</a>
        </div>
        <div class="collapse navbar-collapse">
            
            
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-user"></span> 
                        <strong>{{author}}</strong>
                        <span class="glyphicon glyphicon-chevron-down"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="navbar-login">
                                <div class="row">
                                    <div class="col-lg-4">
                                        <p class="text-center">
                                            <span class="glyphicon glyphicon-user icon-size"></span>
                                        </p>
                                    </div>
                                    <div class="col-lg-8">
                                        <p class="text-left"><strong>{{author}}</strong></p>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="navbar-login navbar-login-session">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <p>
                                            <a href="{% url 'login:auth_logout' %}" class="btn btn-danger btn-block" onclick="return confirm('Keluar?')">Logout</a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="/status/{{author}}">Status</a></li>
                <li><a href="{% url 'profile:index' %}">Profile</a></li> 
                <li><a href="{% url 'teman:index' %}">Teman</a></li>
                <li><a href="{% url 'riwayat:index' %}">Riwayat</a></li>     
             </ul>
            
            
            
        </div>
    </div>
</div>
{% endif %}