login/urls.py
from django.conf.urls import url
from .views import *

# /sol
from .custom_auth import auth_login, auth_logout

urlpatterns = [
	url(r'^$', index, name='index'),

    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout')
    ]

mblepp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import profile_app.urls as profile
import riwayat.urls as riwayat
import login.urls as login
import status.urls as status

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(profile, namespace='profile')),
    url(r'^riwayat/', include(riwayat, namespace='riwayat')),
    url(r'^login/', include(login, namespace='login')),
    url(r'^status/', include(status, namespace='status')),
    url(r'^$', RedirectView.as_view(url="/login/", permanent="true"), name='index'),
]

login/models.py
from django.db import models

# Create your models here.
class User (models.Model):
	nama = models.CharField('Nama', max_length=200)
	kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True)
	role = models.CharField('Role', max_length=100)

login/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import json
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from .models import User


# Create your views here.
response = {'logged_in' : False}
def index(request):
	print ("#==> masuk index")
	if 'user_login' in request.session:
		response['logged_in'] = True
		return HttpResponseRedirect(reverse('profile:index'))
	else:
		response['login'] = False;
		html = 'login/login.html'
		return render(request, html, response)

login/templates/login/login.html
{% extends "login/layout/base.html" %}

{% block content %}

<!-- Content Here -->
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1> Halaman Login </h1>
                <p class="text-info"> Gunakan <b> akun SSO </b> untuk login </p>
            </div>
            <form action="{% url 'login:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Your username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
                    <label for="password"> Your password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input id="login" type="submit" class="btn btn-primary" value="Login">
            </form>
        </div>
    </div>
</div>



{% endblock %}